input {
  beats {
    port => 5044
  }
}

filter {
  if [log_type] == "nginx_access" {
    grok {
      match => { "message" => "%{COMBINEDAPACHELOG}" }
    }
    date {
      match => [ "timestamp", "dd/MMM/yyyy:HH:mm:ss Z" ]
    }
    geoip {
      source => "clientip"
      target => "geoip"
    }
    if [request] =~ /(?i)(select|union|insert|drop|'|--|;)/ {
      mutate {
        add_tag => ["sql_injection_attempt"]
        add_field => { "alert_type" => "SQL_INJECTION" }
      }
    }
    if [response] == "404" {
      mutate {
        add_tag => ["possible_scan"]
      }
    }
    mutate {
      convert => { "response" => "integer" "bytes" => "integer" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "nginx-logs-%{+YYYY.MM.dd}"
  }
}