[DEFAULT]
bantime = 3600
findtime = 60
maxretry = 10

[apache-auth]
enabled = true
port = http,https
filter = apache-auth
logpath = /var/log/apache2/access.log
maxretry = 10
findtime = 60
bantime = 3600

[apache-scan]
enabled = true
port = http,https
filter = apache-scan
logpath = /var/log/apache2/access.log
maxretry = 15
findtime = 60
bantime = 3600